config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'articles#index'
  get 'tags/:tag', to: 'articles#index', as: :tag
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
	acts_as_taggable
	validates :title,  presence: true
	validates :url, 	 presence: true
	validates :source, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :admin_user, only: [:create, :destroy, :new, :update, :show, :edit]

  def index
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all.order('created_at DESC').paginate(page: params[:page], per_page: 9)
    end
  end

  def show
  end

  def new
    @user = User.find_by(params[:id])
    @article = Article.new
  end

  def edit
  end


  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to new_article_path, notice: 'Article was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.' 
    else
      render action: 'edit' 
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url 
  end

private
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :url, :promoted, :tag_list, :source, :twitter_info)
  end

  def admin_user
    if current_user == nil
      redirect_to(root_url)
    else 
      current_user.admin? 
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or new_article_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

	def destroy
		sign_out
		redirect_to root_url
	end

private
  def session_params
    params.require(:session).permit(:remember_token)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
  		flash[:success] = "You got it Pontiac"
  		redirect_to new_article_path
  	else
  		render 'new'
		end
	end

  def show
  	@user = User.find(params[:id])
  end

private 
	
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end


  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas)" %><br />
    <%= f.text_field :tag_list %>
  </div>


  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, rows: 10 %>
  </div>

  <div class="field">
    <%= f.label :url, "Long form URL" %><br>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= f.label :source, "The source of the article shorted for presentation" %><br>
    <%= f.text_field :source %>
  </div>
  
  <div class="field">
    <%= f.label :twitter_info, "Headline followed by | bit.ly link" %><br>
    <%= f.text_field :twitter_info %>
  </div>

  <div class="field">
    <%= f.label :promoted %><br>
    <%= f.check_box :promoted %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
  <div class="wrapper">
  <aside>
    <header>
      <h1><%= link_to 'the junior developer', root_path, class: "title" %></h1>
      <h3 class="sub-heading">
        <span class="label">all the resources, articles and information you'll ever need</span>
        <span class="label">Created by <%= link_to "Me", "http://github.com/jaredphillips", target: "_blank" %></span>
      </h3>
      <%= link_to "subscribe", "http://eepurl.com/Tze0T", class: "button subscribe" %>
      <%= link_to "RSS", articles_url(format: "atom"), class: "button rss" %>
      <%= link_to "twitter", "http://twitter.com/thejrdev", class: "button twitter" %>
    </header>
  </aside>
  <section>
    <% @articles.each do |article| %>
      <div class="article-container">
        <%= link_to article.title, article.url, target: "_blank", class: "article-head" %>
        <p>
          <%= article.description %>
        </p>
        <ul class="tags">
          <li>
            <%= raw article.tag_list.map { |tag| link_to tag, tag_path(tag)}.join(' ') %>
          </li>
        </ul>
      </div>
    <% end %>
    <div class="pagination-buttons">
      <% if params[:tag] %>
        <%= link_to "back", root_path, class: "travel pop" %>
      <% else %>
        <% if @articles.previous_page %>
          <%= link_to "nah, go back", params.merge(page: @articles.previous_page), class: "travel pop" %>
        <% end %>
        <% if @articles.next_page %>  
          <%= link_to "more", params.merge(page: @articles.next_page), class: "travel pop" %>
        <% end %>
      <% end %>
    </div>
  </section>
</div>
<%= render 'layouts/googlescript' %>

app/views/articles/new.html.erb
<div class="wrapper">
	<div class="left">
		<h3>New article</h3>

		<%= gravatar_for @user %>
		<p><%= @user.name %></p>
	</div>
	<div class="right">
		<%= render 'form' %>
	

		<%= link_to 'Back', articles_path %>

		<%= link_to "Sign out", session_path(@user), method: "delete" %>
	</div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @article.url %>
</p>

<p>
  <strong>Promoted:</strong>
  <%= @article.promoted %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_googlescript.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50376086-2', 'thejuniordeveloper.com');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Imprima' rel='stylesheet' type='text/css'>
		<%= favicon_link_tag 'favicon.png' %>
		<%= auto_discovery_link_tag(:atom, articles_url(format: "atom")) %>
	  <title>The Junior Developer</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= yield %>
		<!-- <script src="//code.jquery.com/jquery-1.11.0.min.js"></script> -->
		<!-- <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script> -->
	</body>
</html>

app/views/users/new.html.erb
<!-- <%= form_for(@user) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create my account" %>
<% end %> -->

app/views/users/show.html.erb
<%= gravatar_for @user %>
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>